/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (51.74%)
 * Total Accepted:    115.5K
 * Total Submissions: 223.3K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
    public char findTheDifference(String s, String t) {
        int sCharCodeSum = 0;
        int tCharCodeSum = 0;
        for(int i=0;i<s.length();i++){
            sCharCodeSum += (int)s.charAt(i);
        }
        for(int j=0;j<t.length();j++){
            tCharCodeSum += (int)t.charAt(j);
        }
        return (char)(tCharCodeSum-sCharCodeSum);
    }
}
