/**
 * 
https://www.cnblogs.com/grandyang/p/5261569.html
Given a word, write a function to generate all of its unique generalized abbreviations.

Generalized abbreviation of a word can be generated by replacing each substring of the word by the count of characters in the substring. 
Take the example of “ab” which has four substrings: “”, “a”, “b”, and “ab”. 
After replacing these substrings in the actual word by the count of characters 
we get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.

Example 1:
Input: "BAT"
Output: "BAT", "BA1", "B1T", "B2", "1AT", "1A1", "2T", "3"

Example 2:
Input: "code"
Output: "code", "cod1", "co1e", "co2", "c1de", "c1d1", "c2e", "c3", "1ode", "1od1", "1o1e", "1o2", 
"2de", "2d1", "3e", "4"

code
“”
“_”,                            "c"

"_ _", "_o",                    "c_", "co",

"_ _ _", "_ _ d", "_o_", "_od", "c _ _", "c _ d", "co_", "cod",
*/

import java.util.*;

class AbbreviatedWord {
    String str;
    int length;
    int count;
  
    public AbbreviatedWord(String str, int length, int count) {
      this.str = str;
      this.length = length;
      this.count = count;
    }
  }

class GeneralizedAbbreviation {
    public static List<String> generateGeneralizedAbbreviation(String word) {

        List<String> result = new ArrayList<String>();
        
        int wordLength = word.length();
        char[] chars = word.toCharArray();

        Queue<AbbreviatedWord>queue = new LinkedList<>();
        queue.add(new AbbreviatedWord("", 0, 0));

        for (char c : chars) {
            while(queue.isEmpty() == false){
                //获取
                AbbreviatedWord wordModel = queue.poll();
                if(wordModel.length == wordLength){
                    //收集结果
                    result.add(wordModel.str);
                }else{
                    //缩略
                    queue.add(new AbbreviatedWord(wordModel.str, wordModel.length+1, wordModel.count+1));
    
                    //添加字符
                    StringBuilder sb = new StringBuilder();
                    sb.append(wordModel.str);
                    if(wordModel.count > 0){
                        sb.append(wordModel.count);
                    }
                    sb.append(c);
                    queue.add(new AbbreviatedWord(sb.toString(), wordModel.length+1, 0));
                }
            }
        }
        return result;
    }

  public static void main(String[] args) {
    List<String> result = GeneralizedAbbreviation.generateGeneralizedAbbreviation("BAT");
    System.out.println("Generalized abbreviation are: " + result);

    result = GeneralizedAbbreviation.generateGeneralizedAbbreviation("code");
    System.out.println("Generalized abbreviation are: " + result);
  }
}
